# Micronaut configuration
micronaut:
  ssl:
    port: 443
    enabled: true
    keyStore:
      path: classpath:vf-starter-self-signed.p12
      password: changeit
      type: PKCS12
  application:
    name: starter
  router:
    static-resources:
      ui:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"
      swagger:
        enabled: true
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

# Endpoints config
endpoints:
  health:
    enabled: true

# All VFA Starter configuration
vf-starter:
  base-url: https://localhost
  ui-path: /ui
  default-template: vfa
