# Workflow for building and deploying VF-Starter to AWS.
# Note, please set a GitHub Actions Secret at repository level for `AWS_ROLE_TO_ASSUME` (AWS IAM Role ARN)

name: Build and Deploy VF-Starter

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-west-1

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout@v2

jobs:

  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      #- name: Check out code
      #        uses: actions/checkout@v2
      #
      #      - name: Set up JDK 8
      #        uses: actions/setup-java@v2
      #        with:
      #          java-version: '8'
      #          distribution: 'adopt'
      #
      #      - name: Build with Gradle
      #        run: |
      #          ./gradlew build --no-daemon
      #
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1